apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vakyamanch-instance-pvc
  namespace: vakyamanch-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vakyamanch-uploads-pvc
  namespace: vakyamanch-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi