name: Vakyamanch GKE Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: vakyamanch
  K8S_NAMESPACE: vakyamanch-prod
  GKE_CLUSTER: vakyamanch-gke
  GKE_ZONE: us-central1-a

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify Kubernetes files
        run: |
          ls -la kubernetes/
          cat kubernetes/deployment.yaml

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Process Kubernetes manifests
        run: |
          # Create namespace if not exists
          kubectl create namespace ${{ env.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          
          # Create secret if not exists
          if [ -f .env ]; then
            kubectl create secret generic vakyamanch-secrets \
              --from-env-file=.env \
              --dry-run=client -o yaml | \
              kubectl apply -f - -n ${{ env.K8S_NAMESPACE }}
          fi
          
          # Process all yaml files to replace placeholders
          mkdir -p kubernetes/processed
          for file in kubernetes/*.yaml; do
            sed \
              -e "s/DOCKERHUB_USERNAME_PLACEHOLDER/${{ secrets.DOCKERHUB_USERNAME }}/g" \
              -e "s/\$DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g" \
              "$file" > "kubernetes/processed/$(basename $file)"
          done


      - name: Apply Network Policy
        run: |
          kubectl apply -f - <<EOF
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: vakyamanch-firewall
            namespace: ${{ env.K8S_NAMESPACE }}
          spec:
            podSelector:
              matchLabels:
                app: vakyamanch
            policyTypes:
            - Ingress
            ingress:
            - from:
              - ipBlock:
                  cidr: 0.0.0.0/0
              ports:
              - protocol: TCP
                port: 5000
          EOF

      - name: Apply Kubernetes manifests
        run: |
          # Apply storage classes first if they exist
          if [ -f kubernetes/processed/storage.yaml ]; then
            kubectl apply -f kubernetes/processed/storage.yaml -n ${{ env.K8S_NAMESPACE }}
            sleep 10  # Wait for storage to provision
          fi
          
          # Apply all other manifests
          kubectl apply -f kubernetes/processed/ -n ${{ env.K8S_NAMESPACE }}
          
          # Verify deployment
          kubectl get deployments,pods,services,pvc -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/vakyamanch -n ${{ env.K8S_NAMESPACE }} --timeout=300s
          
          # Debug if PVCs are pending
          kubectl describe pvc -n ${{ env.K8S_NAMESPACE }}
          kubectl get storageclass